project: 'DELTA'
mixed_precision: True
# exp_name: 'mesh'
# training
train:
  batch_size: 1
  max_steps: 10000
  beta_lr: 5e-4
  nerf_lr: 5e-4
  mesh_geo_lr: 1e-3
  mesh_color_lr: 1e-2
  cam_lr: 1e-4
  pose_lr: 1e-4
  exp_lr: 1e-4
  light_lr: 0.
  val_steps: 200
  
# mesh config
use_mesh: False
mesh:
  use_geo: True
  geo_net: 'siren'
  geo_cond_type: None
  geo_scale: 0.004
  geo_out_dim: 1 # 1 or 3, 1 for z, 3 for xyz
  color_net: 'ngp'
  color_cond_type: None
  color_out_dim: 1 # 1 or 3, 1 for z, 3 for xyz

# nerf config
use_nerf: True
nerf:
  near: -1.5
  far: 1.5
  nerf_net: 'ngp'
  nerf_cond: None
  deform_cond: None
  n_rays: 8192 #16384 #32768 # sample rays, to avoid OOM
  n_rays_patch_size: 0
  n_points: 0
  n_coarse_points: 128
  test_n_rays: 8192 #32768
  render_normal: False
# posemodel config
use_posemodel: False #True

# losses
loss:
  alpha_region: all
  w_rgb: 1.
  w_alpha: 0.1 #1
  w_patch_perceptual: 0. #001  #01
  w_reg_correction: 0. #1
  w_reg_normal: 0. #0.1
  w_hard: 0. #1 #1.
  w_hard_scale: 0.
  mesh_rgb_region: skin
  mesh_alpha_region: skin
  mesh_w_rgb: 0. #05
  mesh_w_alpha: 0.
  mesh_w_alpha_inside: 0. #1
  mesh_w_mrf: 0.
  mesh_w_perceptual: 0. #01 #005
  # reg
  mesh_w_reg_offset: 100.
  mesh_w_reg_edge: 1000.

  